### ISSUE TITLE
完成一次操作需要1秒多，感觉远没有达到大佬gif里的效果…

### ISSUE THREAD

**Issue by iPoring** [Sjj1024/QiangCai#12]
<img width="1327" alt="WX20220417-090342@2x" src="https://user-images.githubusercontent.com/34330384/163695959-8c839044-e5c4-4fab-ad71-b406e70b51ea.png">

**Comment by iPoring** [comment]
用的是网易mumu模拟器，mac系统，python3.8

**Comment by iPoring** [comment]
<img width="1327" alt="WX20220417-084835@2x" src="https://user-images.githubusercontent.com/34330384/163695714-be049ca0-035d-48d0-bd2e-5a22559cdf08.png">
操作几次就卡住了...

**Comment by iPoring** [comment]
<img width="1340" alt="WX20220417-085623@2x" src="https://user-images.githubusercontent.com/34330384/163695841-aee7a238-5ed9-425b-baa8-47c85ed15051.png">

**Comment by Sjj1024** [comment]
速度本来就是很慢
