### ISSUE TITLE
每次点击时间好长，大概要接近2s

### ISSUE THREAD

**Issue by Eric-Miao** [Sjj1024/QiangCai#13]
用的鸿蒙OS的实体机在跑测试，发现每次点击的时间都很长，最短也要1s多，最长要5s多。
![image](https://user-images.githubusercontent.com/32360942/163721796-0b43815e-0bf8-439a-8bbc-af7326486406.png)
问题是出在autoui吗，还是在电脑和手机之间的传输？

**Comment by Sjj1024** [comment]
实际速度就是不快的，正常现象，我的gif图片加速了

**Comment by Eric-Miao** [comment]
哦哦，那就好。
还有个问题就是想讨论一下，慢的原因是什么，毕竟只是模拟点击的话应该不会很慢的吧？

**Comment by Sjj1024** [comment]
解析手机界面时间+发送点击指令时间等等，加起来时间就慢了
