### ISSUE TITLE
虚拟机中叮咚买菜apk能推荐一个吗

### ISSUE THREAD

**Issue by lushan88a** [Sjj1024/QiangCai#3]
网上下的apk安装在虚拟机中一直闪退，有可以用的推荐一个吗

**Comment by yilovezy** [comment]
不适配叮咚买菜app，可以用美团买菜app

**Comment by haifengzuishuai** [comment]
> 网上下的apk安装在虚拟机中一直闪退，有可以用的推荐一个吗

你说的哪个apk闪退

**Comment by LZYpaddy** [comment]
> > 网上下的apk安装在虚拟机中一直闪退，有可以用的推荐一个吗
> 
> 你说的哪个apk闪退

叮咚不行，我试了【雷电模拟器】和【网易mumu】都闪退

**Comment by Sjj1024** [comment]
把手机上的apk发送到电脑上，然后用虚拟机安装

**Comment by lautokwah** [comment]
> 把手机上的apk发送到电脑上，然后用虚拟机安装

直接用虚拟机的浏览器访问官网下载安装的，闪退。如果有安卓手机大概也就不用虚拟机了。

**Comment by lushan88a** [comment]
前几天用手点还能抢到 这两天自动化搞了个寂寞。。。。

**Comment by Sjj1024** [comment]
美团外卖下载：https://wwd.lanzouf.com/iGVRg031d9sf
叮咚买菜下载：https://wwd.lanzouf.com/izLDB0362tja

**Comment by lautokwah** [comment]
安装了这个版本的叮咚，还是闪退。（MuMu 模拟器）

> 美团外卖下载：https://wwd.lanzouf.com/iGVRg031d9sf 叮咚买菜下载：https://wwd.lanzouf.com/izLDB0362tja
