### ISSUE TITLE
叮咚买菜可以用，但是美团不会提交订单

### ISSUE THREAD

**Issue by alanleung2017** [Sjj1024/QiangCai#6]
D:\www\github_com\QiangCai\meituan.py:11: DeprecationWarning: Call to deprecated method service. (You should use d.uiautomator.start() instead) -- Deprecated since version 3.0.0.
  if not d.service("uiautomator").running():
D:\www\github_com\QiangCai\meituan.py:17: DeprecationWarning: Call to deprecated function (or staticmethod) agent_alive. (This method will deprecated soon) -- Deprecated since version 3.0.0.
  if not d.agent_alive:
本次花费时间: 2.187417507171631
总共花费时间: 0.036473286151885984 分钟，第 1 次
本次花费时间: 0.7598812580108643
总共花费时间: 0.04918815692265829 分钟，第 2 次
本次花费时间: 0.7427809238433838
总共花费时间: 0.06163778305053711 分钟，第 3 次
本次花费时间: 0.5844407081604004
总共花费时间: 0.07144516309102376 分钟，第 4 次
本次花费时间: 0.6644003391265869
总共花费时间: 0.08261044422785441 分钟，第 5 次
本次花费时间: 0.587352991104126
总共花费时间: 0.0924657940864563 分钟，第 6 次
本次花费时间: 0.5923583507537842
总共花费时间: 0.10238925218582154 分钟，第 7 次
本次花费时间: 0.7009298801422119
总共花费时间: 0.11412132978439331 分钟，第 8 次
本次花费时间: 0.6466548442840576
总共花费时间: 0.12493219375610351 分钟，第 9 次

**Comment by alanleung2017** [comment]
d.app_start("com.meituan.retail.v.android") 换成了美团买菜但是识别不出来立即支付：
if d(text="立即支付").exists:
            print("点击立即支付")
            d(text="立即支付").click()

**Comment by Sjj1024** [comment]
要用美团外卖app里面的美团买菜入口！

**Comment by alanleung2017** [comment]
> 要用美团外卖app里面的美团买菜入口！

我试试，大佬

**Comment by alanleung2017** [comment]
入口在哪里放个截图大佬

**Comment by Sjj1024** [comment]
在美团外卖搜 美团买菜，就可以进去了

**Comment by alanleung2017** [comment]
> 在美团外卖搜 美团买菜，就可以进去了

if d(text="结算(").exists: 这个元素识别不到吧

**Comment by alanleung2017** [comment]
d.app_start("com.sankuai.meituan") 美团外卖的包名也不是这个

**Comment by alanleung2017** [comment]
算了放弃治疗了应该要OCR结算按钮

**Comment by footlose** [comment]
有人改进下脚本吗 确实美团app到不了最后付款页面

**Comment by alanleung2017** [comment]
> 有人改进下脚本吗 确实美团app到不了最后付款页面

美团的现在估计autojspro相关的仓库才能用
