### ISSUE TITLE
这是一种作弊行为！

### ISSUE THREAD

**Issue by tu6ge** [Sjj1024/QiangCai#8]
作为一个程序员，深知掌握技术会有一些优势，但是对于生活物资来讲，不存在程序员就应该优先于其他人获得的情况，考虑一下别人的感受吧

**Comment by Aurora-816** [comment]
怎么配啊 懒得动手指点了

**Comment by ZhuYiXuanNB** [comment]
很有趣的项目👍

**Comment by Sjj1024** [comment]
老子就是会怎么了，物竞天择，优胜略汰，怎么了，你能怎么滴，不喜欢可以gun
